spring.security.oauth2.client.registration.google.client-id=985118957603-ql9cvge7oa52ljvo90nh7o66u1n3oqbd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile